ALTER TABLE drivers ADD COLUMN IF NOT EXISTS license_issuance TIMESTAMP WITH TIME ZONE;

ALTER TABLE vehicles 
ADD COLUMN IF NOT EXISTS rc_issuance TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS insurance_issuance TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS puc_issuance TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS fitness_issuance TIMESTAMP WITH TIME ZONE;
